### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by yagmurbarank**
created index.html

### CODE REVIEW

**Comment by yagmurbarank** [comment]
I added a file

**Review by arzucaner — CHANGES_REQUESTED** [review]
Great job! Thanks Yagmur. But we have index.html on the project. Could you change please this file?

**Comment by yagmurbarank** [comment]
okay I will change the file. Can we add the bootstrap to this project?

**Review by arzucaner — COMMENTED** [review]
Great idea! Normally we can use Bulma but after we can use bootstrap.

**Comment by arzucaner** [comment]
Thanks Yagmur!

**Pull request merged**
